### PR TITLE
utils/load-example: add support for windows

### LINKED ISSUE #28: 'create-next-app --example ...' stuck while 'Downloading files for ... example'
1. `create-next-app --version`: 0.5.2
2. `node --version`: 8.9.3
3. `npm --version`: 5.5.1 or 5.6.0
4. Windows 10

E.g. `create-next-app --example ssr-caching ssr-caching-app` creates two folder 'ssr-caching-app' and '-p' and is stuck on 'Downloading files for ssr-caching example'
I guess the '-p' folder is related to the probem..

Thanks in advance

### PR DESCRIPTION
**Pull request by stephenmathieson**
This patch removes the dependencies on the user having avaiable `curl`, `mkdir` and `tar` commands installed (which Windows often does not). Additionally, rather than using UNIX streams to extract the downloaded archive (which Windows doesn't like), we use native Node streams.

A new check has been added which ensures the provided example name exists. This ensures we don't exit successfully when attempting to untar a directory which doesn't exist (as `tar` doesn't seem to mind this).

Closes #28.

### CODE REVIEW

**Comment by prateekrastogi** [comment]
Hi,

As of now it is still stuck in downloading phase on windows.  But, with git bash it is working properly.

**Comment by stephenmathieson** [comment]
Hey Prateek! Looks like a bug in the CircleCI configuration prevented the last release from making it to npm. I've just pushed an update and v0.5.5 should be available soon.

Sorry for the inconvenience!

**Comment by stephenmathieson** [comment]
Err, nope. CircleCI no longer has permission to run `npm publish`. I'll get the folks at Segment to fix this ASAP.

**Comment by prateekrastogi** [comment]
@stephenmathieson  it maybe due to recent token invalidation of npm due to some eslint malicious publish.

**Comment by stephenmathieson** [comment]
Yep, that's likely it. I've emailed a friend at Segment to see if they can update the token. Stay tuned :)

**Pull request merged**
